platform :ios, '10'
use_frameworks!
inhibit_all_warnings!

target 'DemoApplication' do
    pod 'Alamofire', '~> 4.8.0'
    pod 'AlamofireObjectMapper', '~> 5.2.0'
    pod 'Dip', '~> 7.0.0'
    pod 'RealmSwift', '~> 3.13.0'
end
