platform :ios, '10'
use_frameworks!
inhibit_all_warnings!

target 'DemoApplication' do
    pod 'Alamofire', '~> 4.8.0'
    pod 'AlamofireObjectMapper', '~> 5.2.0'
    pod 'Dip', '~> 7.0.0'
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '4.2'
        end
    end
end
